Repository apache/maven-changes-plugin, pull requests merged in 2025-05, with the labels that each got.

#113 [MCHANGES-466] Add parameter escapeText
  src/it/report-changes-generation-notEscapeText/pom.xml
  src/it/report-changes-generation-notEscapeText/src/changes/changes.xml
  src/it/report-changes-generation-notEscapeText/verify.groovy
  src/it/report-changes-generation/src/changes/changes.xml
  src/it/report-changes-generation/verify.groovy
  src/main/java/org/apache/maven/plugins/changes/ChangesReport.java
  src/main/java/org/apache/maven/plugins/changes/ChangesReportRenderer.java
Labels: enhancement

#127 Escape JIRA reserved words in JqlQueryBuilder
  src/main/java/org/apache/maven/plugins/changes/jira/JqlQueryBuilder.java
  src/test/java/org/apache/maven/plugins/changes/jira/JqlQueryBuilderTestCase.java
Labels: bug

#129 Update site descriptor
  pom.xml
  src/site/site.xml
Labels: maintenance
